services:
  db:
    image: postgres:16
    container_name: audit-db
    restart: always
    environment:
      POSTGRES_DB: audit_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      RETENTION_INTERVAL_SECONDS: "5"
      RETENTION_YEARS: "3"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
