services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: audit_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      # Check that Redis responds
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    environment:
      RETENTION_INTERVAL_SECONDS: "86400"   # 24 hours
      RETENTION_YEARS: "3"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
