"""create audit_events table

Revision ID: 9085549f9274
Revises: 
Create Date: 2025-08-07 19:35:34.628531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9085549f9274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('log_type', sa.Enum('Login', 'System', 'Management', name='logtype_enum'), nullable=False),
    sa.Column('reporting_service', sa.UUID(), nullable=False),
    sa.Column('log_level', sa.Enum('informational', 'warning', 'error', name='loglevel_enum'), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('identity_type', sa.Enum('User', 'Application', 'API Key', name='identitytype_enum'), nullable=False),
    sa.Column('user', sa.JSON(), nullable=False),
    sa.Column('action', sa.Enum('Access', 'Approve', 'Create', 'Update', 'Delete', 'Deny', 'Execute', 'Notify', 'Revoke', 'Export', name='action_enum'), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # Create an index on ingested_at for faster queries
    op.create_index('ix_audit_events_ingested_at', 'audit_events', ['ingested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_events')
    op.drop_index("ix_audit_events_ingested_at", table_name="audit_events")
    # ### end Alembic commands ###
